; Stunnel — SSH SSL backend.
; Public reachable on 443 via Nginx stream multiplexer (no SNI -> here).

cert    = /etc/stunnel/stunnel.pem
client  = no
pid     = /var/run/stunnel.pid
output  = /var/log/stunnel.log
debug   = 4
sslVersion = all

[ssh-ssl-backend]
accept  = 127.0.0.1:7443
connect = 127.0.0.1:22

[ssh-ssl-public]
accept  = 0.0.0.0:777
connect = 127.0.0.1:22
